//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class xcdconapl_cl
    {
        public string tipdoc_cve { get; set; }
        public string sp_cve { get; set; }
        public short num_reng { get; set; }
        public string spd_cve { get; set; }
        public string prm1 { get; set; }
        public string prm2 { get; set; }
        public string prm3 { get; set; }
        public string prm4 { get; set; }
        public string prm5 { get; set; }
        public string prm6 { get; set; }
        public string prm7 { get; set; }
        public string prm8 { get; set; }
        public string prm9 { get; set; }
        public string prm10 { get; set; }
        public string prm11 { get; set; }
        public string prm12 { get; set; }
        public string prm13 { get; set; }
        public Nullable<short> prm14 { get; set; }
        public Nullable<decimal> prm15 { get; set; }
        public string prm16 { get; set; }
    }
}
