//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class xcuser
    {
        public string ef_cve { get; set; }
        public string div_cve { get; set; }
        public string user_cve { get; set; }
        public string nombre { get; set; }
        public string password { get; set; }
        public string dest_mail { get; set; }
        public string idioma { get; set; }
        public string srv_cve { get; set; }
        public string path_adobe { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<short> sw_password { get; set; }
    }
}
