//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class skytexEntities : DbContext
    {
        public skytexEntities()
            : base("name=skytexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<xcuser> xcuser { get; set; }
        public virtual DbSet<xcdconapl_cl> xcdconapl_cl { get; set; }
        public virtual DbSet<itmov> itmov { get; set; }
        public virtual DbSet<xcdivef> xcdivef { get; set; }
        public virtual DbSet<xuarttip> xuarttip { get; set; }
        public virtual DbSet<xufolios> xufolios { get; set; }
    
        public virtual ObjectResult<sp_webAppSalaCbo_Result> sp_webAppSalaCbo(string ef_cve, string movimiento, string extra1, string extra2, string extra3, string extra4)
        {
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            var movimientoParameter = movimiento != null ?
                new ObjectParameter("movimiento", movimiento) :
                new ObjectParameter("movimiento", typeof(string));
    
            var extra1Parameter = extra1 != null ?
                new ObjectParameter("extra1", extra1) :
                new ObjectParameter("extra1", typeof(string));
    
            var extra2Parameter = extra2 != null ?
                new ObjectParameter("extra2", extra2) :
                new ObjectParameter("extra2", typeof(string));
    
            var extra3Parameter = extra3 != null ?
                new ObjectParameter("extra3", extra3) :
                new ObjectParameter("extra3", typeof(string));
    
            var extra4Parameter = extra4 != null ?
                new ObjectParameter("extra4", extra4) :
                new ObjectParameter("extra4", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_webAppSalaCbo_Result>("sp_webAppSalaCbo", ef_cveParameter, movimientoParameter, extra1Parameter, extra2Parameter, extra3Parameter, extra4Parameter);
        }
    
        public virtual ObjectResult<qcomsala1_Result> qcomsala1(string tipdoc_cve, string movimiento)
        {
            var tipdoc_cveParameter = tipdoc_cve != null ?
                new ObjectParameter("tipdoc_cve", tipdoc_cve) :
                new ObjectParameter("tipdoc_cve", typeof(string));
    
            var movimientoParameter = movimiento != null ?
                new ObjectParameter("movimiento", movimiento) :
                new ObjectParameter("movimiento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<qcomsala1_Result>("qcomsala1", tipdoc_cveParameter, movimientoParameter);
        }
    
        public virtual ObjectResult<qcomtiptra1_Result> qcomtiptra1(string tipdoc_cve)
        {
            var tipdoc_cveParameter = tipdoc_cve != null ?
                new ObjectParameter("tipdoc_cve", tipdoc_cve) :
                new ObjectParameter("tipdoc_cve", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<qcomtiptra1_Result>("qcomtiptra1", tipdoc_cveParameter);
        }
    
        public virtual int sp_insdet(string ef_cve, string tipo_doc, Nullable<int> num_fol, string desc_op, string lote_num, Nullable<System.DateTime> lote_fec)
        {
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            var tipo_docParameter = tipo_doc != null ?
                new ObjectParameter("tipo_doc", tipo_doc) :
                new ObjectParameter("tipo_doc", typeof(string));
    
            var num_folParameter = num_fol.HasValue ?
                new ObjectParameter("num_fol", num_fol) :
                new ObjectParameter("num_fol", typeof(int));
    
            var desc_opParameter = desc_op != null ?
                new ObjectParameter("desc_op", desc_op) :
                new ObjectParameter("desc_op", typeof(string));
    
            var lote_numParameter = lote_num != null ?
                new ObjectParameter("lote_num", lote_num) :
                new ObjectParameter("lote_num", typeof(string));
    
            var lote_fecParameter = lote_fec.HasValue ?
                new ObjectParameter("lote_fec", lote_fec) :
                new ObjectParameter("lote_fec", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insdet", ef_cveParameter, tipo_docParameter, num_folParameter, desc_opParameter, lote_numParameter, lote_fecParameter);
        }
    
        public virtual int sp_insenc(string ef_cve, string tipdoc_cve, Nullable<System.DateTime> fec_ultact, Nullable<System.DateTime> fec_prom, Nullable<System.DateTime> fec_mov, string imp_letra, string fec_letra, string refer)
        {
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            var tipdoc_cveParameter = tipdoc_cve != null ?
                new ObjectParameter("tipdoc_cve", tipdoc_cve) :
                new ObjectParameter("tipdoc_cve", typeof(string));
    
            var fec_ultactParameter = fec_ultact.HasValue ?
                new ObjectParameter("fec_ultact", fec_ultact) :
                new ObjectParameter("fec_ultact", typeof(System.DateTime));
    
            var fec_promParameter = fec_prom.HasValue ?
                new ObjectParameter("fec_prom", fec_prom) :
                new ObjectParameter("fec_prom", typeof(System.DateTime));
    
            var fec_movParameter = fec_mov.HasValue ?
                new ObjectParameter("fec_mov", fec_mov) :
                new ObjectParameter("fec_mov", typeof(System.DateTime));
    
            var imp_letraParameter = imp_letra != null ?
                new ObjectParameter("imp_letra", imp_letra) :
                new ObjectParameter("imp_letra", typeof(string));
    
            var fec_letraParameter = fec_letra != null ?
                new ObjectParameter("fec_letra", fec_letra) :
                new ObjectParameter("fec_letra", typeof(string));
    
            var referParameter = refer != null ?
                new ObjectParameter("refer", refer) :
                new ObjectParameter("refer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insenc", ef_cveParameter, tipdoc_cveParameter, fec_ultactParameter, fec_promParameter, fec_movParameter, imp_letraParameter, fec_letraParameter, referParameter);
        }
    
        public virtual ObjectResult<string> qcomarea1(string ef_cve)
        {
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("qcomarea1", ef_cveParameter);
        }
    
        public virtual ObjectResult<qcomare1_Result> qcomare1(string ef_cve, string prg_cve)
        {
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            var prg_cveParameter = prg_cve != null ?
                new ObjectParameter("prg_cve", prg_cve) :
                new ObjectParameter("prg_cve", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<qcomare1_Result>("qcomare1", ef_cveParameter, prg_cveParameter);
        }
    
        public virtual ObjectResult<string> sp_HoraFin(Nullable<System.DateTime> fecha, string tipo_doc, string refer)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var tipo_docParameter = tipo_doc != null ?
                new ObjectParameter("tipo_doc", tipo_doc) :
                new ObjectParameter("tipo_doc", typeof(string));
    
            var referParameter = refer != null ?
                new ObjectParameter("refer", refer) :
                new ObjectParameter("refer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_HoraFin", fechaParameter, tipo_docParameter, referParameter);
        }
    
        public virtual ObjectResult<string> qcomFiltra(string tipo_doc, string refer, Nullable<System.DateTime> fechaCita)
        {
            var tipo_docParameter = tipo_doc != null ?
                new ObjectParameter("tipo_doc", tipo_doc) :
                new ObjectParameter("tipo_doc", typeof(string));
    
            var referParameter = refer != null ?
                new ObjectParameter("refer", refer) :
                new ObjectParameter("refer", typeof(string));
    
            var fechaCitaParameter = fechaCita.HasValue ?
                new ObjectParameter("fechaCita", fechaCita) :
                new ObjectParameter("fechaCita", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("qcomFiltra", tipo_docParameter, referParameter, fechaCitaParameter);
        }
    
        public virtual ObjectResult<sp_FiltraHoraSalida_Result> sp_FiltraHoraSalida(string tipdoc_cve, Nullable<System.DateTime> fecha, string refer, string horaE)
        {
            var tipdoc_cveParameter = tipdoc_cve != null ?
                new ObjectParameter("tipdoc_cve", tipdoc_cve) :
                new ObjectParameter("tipdoc_cve", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var referParameter = refer != null ?
                new ObjectParameter("refer", refer) :
                new ObjectParameter("refer", typeof(string));
    
            var horaEParameter = horaE != null ?
                new ObjectParameter("horaE", horaE) :
                new ObjectParameter("horaE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_FiltraHoraSalida_Result>("sp_FiltraHoraSalida", tipdoc_cveParameter, fechaParameter, referParameter, horaEParameter);
        }
    
        public virtual ObjectResult<qcomhora1_Result> qcomhora1(string tipdoc_cve, Nullable<System.DateTime> fecha, string refer, string ef_cve)
        {
            var tipdoc_cveParameter = tipdoc_cve != null ?
                new ObjectParameter("tipdoc_cve", tipdoc_cve) :
                new ObjectParameter("tipdoc_cve", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var referParameter = refer != null ?
                new ObjectParameter("refer", refer) :
                new ObjectParameter("refer", typeof(string));
    
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<qcomhora1_Result>("qcomhora1", tipdoc_cveParameter, fechaParameter, referParameter, ef_cveParameter);
        }
    
        public virtual ObjectResult<sp_InsertarDetalleCitas_Result> sp_InsertarDetalleCitas(string ef_cve, string tipo_doc, Nullable<int> num_fol, string desc_op, string lote_num, Nullable<System.DateTime> lote_fec, string art_tip, string sku_cve)
        {
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            var tipo_docParameter = tipo_doc != null ?
                new ObjectParameter("tipo_doc", tipo_doc) :
                new ObjectParameter("tipo_doc", typeof(string));
    
            var num_folParameter = num_fol.HasValue ?
                new ObjectParameter("num_fol", num_fol) :
                new ObjectParameter("num_fol", typeof(int));
    
            var desc_opParameter = desc_op != null ?
                new ObjectParameter("desc_op", desc_op) :
                new ObjectParameter("desc_op", typeof(string));
    
            var lote_numParameter = lote_num != null ?
                new ObjectParameter("lote_num", lote_num) :
                new ObjectParameter("lote_num", typeof(string));
    
            var lote_fecParameter = lote_fec.HasValue ?
                new ObjectParameter("lote_fec", lote_fec) :
                new ObjectParameter("lote_fec", typeof(System.DateTime));
    
            var art_tipParameter = art_tip != null ?
                new ObjectParameter("art_tip", art_tip) :
                new ObjectParameter("art_tip", typeof(string));
    
            var sku_cveParameter = sku_cve != null ?
                new ObjectParameter("sku_cve", sku_cve) :
                new ObjectParameter("sku_cve", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_InsertarDetalleCitas_Result>("sp_InsertarDetalleCitas", ef_cveParameter, tipo_docParameter, num_folParameter, desc_opParameter, lote_numParameter, lote_fecParameter, art_tipParameter, sku_cveParameter);
        }
    
        public virtual ObjectResult<qcomWebHora_Result> qcomWebHora(string tipdoc_cve, Nullable<System.DateTime> fecha, string refer, string hora, string ef_cve, Nullable<short> id_pant, Nullable<System.DateTime> fec_salida)
        {
            var tipdoc_cveParameter = tipdoc_cve != null ?
                new ObjectParameter("tipdoc_cve", tipdoc_cve) :
                new ObjectParameter("tipdoc_cve", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var referParameter = refer != null ?
                new ObjectParameter("refer", refer) :
                new ObjectParameter("refer", typeof(string));
    
            var horaParameter = hora != null ?
                new ObjectParameter("hora", hora) :
                new ObjectParameter("hora", typeof(string));
    
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            var id_pantParameter = id_pant.HasValue ?
                new ObjectParameter("Id_pant", id_pant) :
                new ObjectParameter("Id_pant", typeof(short));
    
            var fec_salidaParameter = fec_salida.HasValue ?
                new ObjectParameter("fec_salida", fec_salida) :
                new ObjectParameter("fec_salida", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<qcomWebHora_Result>("qcomWebHora", tipdoc_cveParameter, fechaParameter, referParameter, horaParameter, ef_cveParameter, id_pantParameter, fec_salidaParameter);
        }
    
        public virtual ObjectResult<sp_ConsCitasCalendario_Result> sp_ConsCitasCalendario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsCitasCalendario_Result>("sp_ConsCitasCalendario");
        }
    
        public virtual ObjectResult<sp_AutValCita_Result> sp_AutValCita(string ef_cve, string tipo_doc, Nullable<int> num_fol, Nullable<int> cve_status, Nullable<int> sw_terminado, Nullable<int> sw_si_no, string id_ultact, string obs, Nullable<System.DateTime> fec_ultact, Nullable<System.DateTime> fec_prom, string refer)
        {
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            var tipo_docParameter = tipo_doc != null ?
                new ObjectParameter("tipo_doc", tipo_doc) :
                new ObjectParameter("tipo_doc", typeof(string));
    
            var num_folParameter = num_fol.HasValue ?
                new ObjectParameter("num_fol", num_fol) :
                new ObjectParameter("num_fol", typeof(int));
    
            var cve_statusParameter = cve_status.HasValue ?
                new ObjectParameter("cve_status", cve_status) :
                new ObjectParameter("cve_status", typeof(int));
    
            var sw_terminadoParameter = sw_terminado.HasValue ?
                new ObjectParameter("sw_terminado", sw_terminado) :
                new ObjectParameter("sw_terminado", typeof(int));
    
            var sw_si_noParameter = sw_si_no.HasValue ?
                new ObjectParameter("sw_si_no", sw_si_no) :
                new ObjectParameter("sw_si_no", typeof(int));
    
            var id_ultactParameter = id_ultact != null ?
                new ObjectParameter("id_ultact", id_ultact) :
                new ObjectParameter("id_ultact", typeof(string));
    
            var obsParameter = obs != null ?
                new ObjectParameter("obs", obs) :
                new ObjectParameter("obs", typeof(string));
    
            var fec_ultactParameter = fec_ultact.HasValue ?
                new ObjectParameter("fec_ultact", fec_ultact) :
                new ObjectParameter("fec_ultact", typeof(System.DateTime));
    
            var fec_promParameter = fec_prom.HasValue ?
                new ObjectParameter("fec_prom", fec_prom) :
                new ObjectParameter("fec_prom", typeof(System.DateTime));
    
            var referParameter = refer != null ?
                new ObjectParameter("refer", refer) :
                new ObjectParameter("refer", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AutValCita_Result>("sp_AutValCita", ef_cveParameter, tipo_docParameter, num_folParameter, cve_statusParameter, sw_terminadoParameter, sw_si_noParameter, id_ultactParameter, obsParameter, fec_ultactParameter, fec_promParameter, referParameter);
        }
    
        public virtual ObjectResult<sp_InsertarEncabezadoCitas_Result> sp_InsertarEncabezadoCitas(string ef_cve, string tipdoc_cve, Nullable<System.DateTime> fec_ultact, Nullable<System.DateTime> fec_prom, string imp_letra, string fec_letra, string refer, string id_ultact, Nullable<short> plazo, string suc_aten, string obs, string pr5, string pr1, string uuid)
        {
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            var tipdoc_cveParameter = tipdoc_cve != null ?
                new ObjectParameter("tipdoc_cve", tipdoc_cve) :
                new ObjectParameter("tipdoc_cve", typeof(string));
    
            var fec_ultactParameter = fec_ultact.HasValue ?
                new ObjectParameter("fec_ultact", fec_ultact) :
                new ObjectParameter("fec_ultact", typeof(System.DateTime));
    
            var fec_promParameter = fec_prom.HasValue ?
                new ObjectParameter("fec_prom", fec_prom) :
                new ObjectParameter("fec_prom", typeof(System.DateTime));
    
            var imp_letraParameter = imp_letra != null ?
                new ObjectParameter("imp_letra", imp_letra) :
                new ObjectParameter("imp_letra", typeof(string));
    
            var fec_letraParameter = fec_letra != null ?
                new ObjectParameter("fec_letra", fec_letra) :
                new ObjectParameter("fec_letra", typeof(string));
    
            var referParameter = refer != null ?
                new ObjectParameter("refer", refer) :
                new ObjectParameter("refer", typeof(string));
    
            var id_ultactParameter = id_ultact != null ?
                new ObjectParameter("id_ultact", id_ultact) :
                new ObjectParameter("id_ultact", typeof(string));
    
            var plazoParameter = plazo.HasValue ?
                new ObjectParameter("plazo", plazo) :
                new ObjectParameter("plazo", typeof(short));
    
            var suc_atenParameter = suc_aten != null ?
                new ObjectParameter("suc_aten", suc_aten) :
                new ObjectParameter("suc_aten", typeof(string));
    
            var obsParameter = obs != null ?
                new ObjectParameter("obs", obs) :
                new ObjectParameter("obs", typeof(string));
    
            var pr5Parameter = pr5 != null ?
                new ObjectParameter("pr5", pr5) :
                new ObjectParameter("pr5", typeof(string));
    
            var pr1Parameter = pr1 != null ?
                new ObjectParameter("pr1", pr1) :
                new ObjectParameter("pr1", typeof(string));
    
            var uuidParameter = uuid != null ?
                new ObjectParameter("uuid", uuid) :
                new ObjectParameter("uuid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_InsertarEncabezadoCitas_Result>("sp_InsertarEncabezadoCitas", ef_cveParameter, tipdoc_cveParameter, fec_ultactParameter, fec_promParameter, imp_letraParameter, fec_letraParameter, referParameter, id_ultactParameter, plazoParameter, suc_atenParameter, obsParameter, pr5Parameter, pr1Parameter, uuidParameter);
        }
    
        public virtual ObjectResult<sp_consCitas_Result> sp_consCitas(string tipdoc_cve, string opc, string user_cve, Nullable<System.DateTime> fecha)
        {
            var tipdoc_cveParameter = tipdoc_cve != null ?
                new ObjectParameter("tipdoc_cve", tipdoc_cve) :
                new ObjectParameter("tipdoc_cve", typeof(string));
    
            var opcParameter = opc != null ?
                new ObjectParameter("opc", opc) :
                new ObjectParameter("opc", typeof(string));
    
            var user_cveParameter = user_cve != null ?
                new ObjectParameter("user_cve", user_cve) :
                new ObjectParameter("user_cve", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consCitas_Result>("sp_consCitas", tipdoc_cveParameter, opcParameter, user_cveParameter, fechaParameter);
        }
    
        public virtual ObjectResult<qcomWebHoraReagenda_Result> qcomWebHoraReagenda(string tipdoc_cve, string fecha, string refer, string hora, string ef_cve, Nullable<short> id_pant, string fec_salida, Nullable<int> num_fol)
        {
            var tipdoc_cveParameter = tipdoc_cve != null ?
                new ObjectParameter("tipdoc_cve", tipdoc_cve) :
                new ObjectParameter("tipdoc_cve", typeof(string));
    
            var fechaParameter = fecha != null ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(string));
    
            var referParameter = refer != null ?
                new ObjectParameter("refer", refer) :
                new ObjectParameter("refer", typeof(string));
    
            var horaParameter = hora != null ?
                new ObjectParameter("hora", hora) :
                new ObjectParameter("hora", typeof(string));
    
            var ef_cveParameter = ef_cve != null ?
                new ObjectParameter("ef_cve", ef_cve) :
                new ObjectParameter("ef_cve", typeof(string));
    
            var id_pantParameter = id_pant.HasValue ?
                new ObjectParameter("Id_pant", id_pant) :
                new ObjectParameter("Id_pant", typeof(short));
    
            var fec_salidaParameter = fec_salida != null ?
                new ObjectParameter("fec_salida", fec_salida) :
                new ObjectParameter("fec_salida", typeof(string));
    
            var num_folParameter = num_fol.HasValue ?
                new ObjectParameter("num_fol", num_fol) :
                new ObjectParameter("num_fol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<qcomWebHoraReagenda_Result>("qcomWebHoraReagenda", tipdoc_cveParameter, fechaParameter, referParameter, horaParameter, ef_cveParameter, id_pantParameter, fec_salidaParameter, num_folParameter);
        }
    }
}
