//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class xcdivef
    {
        public string ef_cve { get; set; }
        public string div_cve { get; set; }
        public string nombre { get; set; }
        public string bgt_grp { get; set; }
        public string bgt_sgrp { get; set; }
        public string div_grp { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
